<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('codeISO2', 2);
            $table->string('codeISO3', 3);
            $table->string('country_es');
            $table->string('tel_prefix');
            $table->string('language_field'); // Campo para identificador de idioma
            $table->timestamps();
        });

        DB::table('countries')->insert([
            ['codeISO2' => 'AF', 'codeISO3' => 'AFG', 'country_es' => 'Afganistán', 'tel_prefix' => '+93', 'language_field' => 'afghanistan'],
            ['codeISO2' => 'AL', 'codeISO3' => 'ALB', 'country_es' => 'Albania', 'tel_prefix' => '+355', 'language_field' => 'albania'],
            ['codeISO2' => 'DE', 'codeISO3' => 'DEU', 'country_es' => 'Alemania', 'tel_prefix' => '+49', 'language_field' => 'germany'],
            ['codeISO2' => 'AD', 'codeISO3' => 'AND', 'country_es' => 'Andorra', 'tel_prefix' => '+376', 'language_field' => 'andorra'],
            ['codeISO2' => 'AO', 'codeISO3' => 'AGO', 'country_es' => 'Angola', 'tel_prefix' => '+244', 'language_field' => 'angola'],
            ['codeISO2' => 'AI', 'codeISO3' => 'AIA', 'country_es' => 'Anguila', 'tel_prefix' => '+1 264', 'language_field' => 'anguila'],
            ['codeISO2' => 'AQ', 'codeISO3' => 'ATA', 'country_es' => 'Antártida', 'tel_prefix' => '+672', 'language_field' => 'antarctica'],
            ['codeISO2' => 'SA', 'codeISO3' => 'SAU', 'country_es' => 'Arabia Saudita', 'tel_prefix' => '+966', 'language_field' => 'saudi_arabia'],
            ['codeISO2' => 'DZ', 'codeISO3' => 'DZA', 'country_es' => 'Argelia', 'tel_prefix' => '+213', 'language_field' => 'algeria'],
            ['codeISO2' => 'AR', 'codeISO3' => 'ARG', 'country_es' => 'Argentina', 'tel_prefix' => '+54', 'language_field' => 'argentina'],
            ['codeISO2' => 'AM', 'codeISO3' => 'ARM', 'country_es' => 'Armenia', 'tel_prefix' => '+374', 'language_field' => 'armenia'],
            ['codeISO2' => 'AW', 'codeISO3' => 'ABW', 'country_es' => 'Aruba', 'tel_prefix' => '+297', 'language_field' => 'aruba'],
            ['codeISO2' => 'AU', 'codeISO3' => 'AUS', 'country_es' => 'Australia', 'tel_prefix' => '+61', 'language_field' => 'australia'],
            ['codeISO2' => 'AT', 'codeISO3' => 'AUT', 'country_es' => 'Austria', 'tel_prefix' => '+43', 'language_field' => 'austria'],
            ['codeISO2' => 'AZ', 'codeISO3' => 'AZE', 'country_es' => 'Azerbaiyán', 'tel_prefix' => '+994', 'language_field' => 'azerbaijan'],
            ['codeISO2' => 'BS', 'codeISO3' => 'BHS', 'country_es' => 'Bahamas', 'tel_prefix' => '+1', 'language_field' => 'bahamas'],
            ['codeISO2' => 'BH', 'codeISO3' => 'BHR', 'country_es' => 'Bahréin', 'tel_prefix' => '+973', 'language_field' => 'bahrein'],
            ['codeISO2' => 'BD', 'codeISO3' => 'BGD', 'country_es' => 'Bangladesh', 'tel_prefix' => '+880', 'language_field' => 'bangladesh'],
            ['codeISO2' => 'BB', 'codeISO3' => 'BRB', 'country_es' => 'Barbados', 'tel_prefix' => '+1', 'language_field' => 'barbados'],
            ['codeISO2' => 'BE', 'codeISO3' => 'BEL', 'country_es' => 'Bélgica', 'tel_prefix' => '+32', 'language_field' => 'belgica'],
            ['codeISO2' => 'BZ', 'codeISO3' => 'BLZ', 'country_es' => 'Belice', 'tel_prefix' => '+501', 'language_field' => 'belice'],
            ['codeISO2' => 'BJ', 'codeISO3' => 'BEN', 'country_es' => 'Benín', 'tel_prefix' => '+229', 'language_field' => 'benin'],
            ['codeISO2' => 'BM', 'codeISO3' => 'BMU', 'country_es' => 'Bermudas', 'tel_prefix' => '+1', 'language_field' => 'bermudas'],
            ['codeISO2' => 'BY', 'codeISO3' => 'BLR', 'country_es' => 'Bielorrusia', 'tel_prefix' => '+375', 'language_field' => 'bielorrusia'],
            ['codeISO2' => 'MM', 'codeISO3' => 'MMR', 'country_es' => 'Birmania (Myanmar)', 'tel_prefix' => '+95', 'language_field' => 'birmania'],
            ['codeISO2' => 'BO', 'codeISO3' => 'BOL', 'country_es' => 'Bolivia', 'tel_prefix' => '+591', 'language_field' => 'bolivia'],
            ['codeISO2' => 'BA', 'codeISO3' => 'BIH', 'country_es' => 'Bosnia y Herzegovina', 'tel_prefix' => '+387', 'language_field' => 'bosnia_y_herzegovina'],
            ['codeISO2' => 'BW', 'codeISO3' => 'BWA', 'country_es' => 'Botsuana', 'tel_prefix' => '+267', 'language_field' => 'botsuana'],
            ['codeISO2' => 'BR', 'codeISO3' => 'BRA', 'country_es' => 'Brasil', 'tel_prefix' => '+55', 'language_field' => 'brasil'],
            ['codeISO2' => 'BN', 'codeISO3' => 'BRN', 'country_es' => 'Brunéi', 'tel_prefix' => '+673', 'language_field' => 'brunei'],
            ['codeISO2' => 'BG', 'codeISO3' => 'BGR', 'country_es' => 'Bulgaria', 'tel_prefix' => '+359', 'language_field' => 'bulgaria'],
            ['codeISO2' => 'BF', 'codeISO3' => 'BFA', 'country_es' => 'Burkina Faso', 'tel_prefix' => '+226', 'language_field' => 'burkina_faso'],
            ['codeISO2' => 'BI', 'codeISO3' => 'BDI', 'country_es' => 'Burundi', 'tel_prefix' => '+257', 'language_field' => 'burundi'],
            ['codeISO2' => 'BT', 'codeISO3' => 'BTN', 'country_es' => 'Bután', 'tel_prefix' => '+975', 'language_field' => 'butan'],
            ['codeISO2' => 'CV', 'codeISO3' => 'CPV', 'country_es' => 'Cabo Verde', 'tel_prefix' => '+238', 'language_field' => 'cabo_verde'],
            ['codeISO2' => 'KH', 'codeISO3' => 'KHM', 'country_es' => 'Camboya', 'tel_prefix' => '+855', 'language_field' => 'camboya'],
            ['codeISO2' => 'CM', 'codeISO3' => 'CMR', 'country_es' => 'Camerún', 'tel_prefix' => '+237', 'language_field' => 'camerun'],
            ['codeISO2' => 'CA', 'codeISO3' => 'CAN', 'country_es' => 'Canadá', 'tel_prefix' => '+1', 'language_field' => 'canada'],
            ['codeISO2' => 'CL', 'codeISO3' => 'CHL', 'country_es' => 'Chile', 'tel_prefix' => '+56', 'language_field' => 'chile'],
            ['codeISO2' => 'CN', 'codeISO3' => 'CHN', 'country_es' => 'China', 'tel_prefix' => '+86', 'language_field' => 'china'],
            ['codeISO2' => 'CY', 'codeISO3' => 'CYP', 'country_es' => 'Chipre', 'tel_prefix' => '+357', 'language_field' => 'chipre'],
            ['codeISO2' => 'CO', 'codeISO3' => 'COL', 'country_es' => 'Colombia', 'tel_prefix' => '+57', 'language_field' => 'colombia'],
            ['codeISO2' => 'KM', 'codeISO3' => 'COM', 'country_es' => 'Comoras', 'tel_prefix' => '+269', 'language_field' => 'comoras'],
            ['codeISO2' => 'KP', 'codeISO3' => 'PRK', 'country_es' => 'Corea del Norte', 'tel_prefix' => '+850', 'language_field' => 'corea_del_norte'],
            ['codeISO2' => 'KR', 'codeISO3' => 'KOR', 'country_es' => 'Corea del Sur', 'tel_prefix' => '+82', 'language_field' => 'corea_del_sur'],
            ['codeISO2' => 'CI', 'codeISO3' => 'CIV', 'country_es' => 'Costa de Marfil', 'tel_prefix' => '+225', 'language_field' => 'costa_de_marfil'],
            ['codeISO2' => 'CR', 'codeISO3' => 'CRI', 'country_es' => 'Costa Rica', 'tel_prefix' => '+506', 'language_field' => 'costa_rica'],
            ['codeISO2' => 'HR', 'codeISO3' => 'HRV', 'country_es' => 'Croacia', 'tel_prefix' => '+385', 'language_field' => 'croacia'],
            ['codeISO2' => 'CU', 'codeISO3' => 'CUB', 'country_es' => 'Cuba', 'tel_prefix' => '+53', 'language_field' => 'cuba'],
            ['codeISO2' => 'CW', 'codeISO3' => 'CUW', 'country_es' => 'Curazao', 'tel_prefix' => '+599', 'language_field' => 'curazao'],
            ['codeISO2' => 'DK', 'codeISO3' => 'DNK', 'country_es' => 'Dinamarca', 'tel_prefix' => '+45', 'language_field' => 'dinamarca'],
            ['codeISO2' => 'DJ', 'codeISO3' => 'DJI', 'country_es' => 'Djibuti', 'tel_prefix' => '+253', 'language_field' => 'djibuti'],
            ['codeISO2' => 'DM', 'codeISO3' => 'DMA', 'country_es' => 'Dominica', 'tel_prefix' => '+1', 'language_field' => 'dominica'],
            ['codeISO2' => 'EC', 'codeISO3' => 'ECU', 'country_es' => 'Ecuador', 'tel_prefix' => '+593', 'language_field' => 'ecuador'],
            ['codeISO2' => 'EG', 'codeISO3' => 'EGY', 'country_es' => 'Egipto', 'tel_prefix' => '+20', 'language_field' => 'egipto'],
            ['codeISO2' => 'EH', 'codeISO3' => 'ESH', 'country_es' => 'El Sáhara Español', 'tel_prefix' => '+212', 'language_field' => 'el_sahara_espanol'],
            ['codeISO2' => 'SV', 'codeISO3' => 'SLV', 'country_es' => 'El Salvador', 'tel_prefix' => '+503', 'language_field' => 'el_salvador'],
            ['codeISO2' => 'VA', 'codeISO3' => 'VAT', 'country_es' => 'El Vaticano', 'tel_prefix' => '+39', 'language_field' => 'el_vaticano'],
            ['codeISO2' => 'AE', 'codeISO3' => 'ARE', 'country_es' => 'Emiratos Árabes Unidos', 'tel_prefix' => '+971', 'language_field' => 'emiratos_arabes_unidos'],
            ['codeISO2' => 'ER', 'codeISO3' => 'ERI', 'country_es' => 'Eritrea', 'tel_prefix' => '+291', 'language_field' => 'eritrea'],
            ['codeISO2' => 'SK', 'codeISO3' => 'SVK', 'country_es' => 'Eslovaquia', 'tel_prefix' => '+421', 'language_field' => 'eslovaquia'],
            ['codeISO2' => 'SI', 'codeISO3' => 'SVN', 'country_es' => 'Eslovenia', 'tel_prefix' => '+386', 'language_field' => 'eslovenia'],
            ['codeISO2' => 'ES', 'codeISO3' => 'ESP', 'country_es' => 'España', 'tel_prefix' => '+34', 'language_field' => 'espana'],
            ['codeISO2' => 'US', 'codeISO3' => 'USA', 'country_es' => 'Estados Unidos', 'tel_prefix' => '+1', 'language_field' => 'estados_unidos'],
            ['codeISO2' => 'EE', 'codeISO3' => 'EST', 'country_es' => 'Estonia', 'tel_prefix' => '+372', 'language_field' => 'estonia'],
            ['codeISO2' => 'ET', 'codeISO3' => 'ETH', 'country_es' => 'Etiopía', 'tel_prefix' => '+251', 'language_field' => 'etiopia'],
            ['codeISO2' => 'PH', 'codeISO3' => 'PHL', 'country_es' => 'Filipinas', 'tel_prefix' => '+63', 'language_field' => 'filipinas'],
            ['codeISO2' => 'FI', 'codeISO3' => 'FIN', 'country_es' => 'Finlandia', 'tel_prefix' => '+358', 'language_field' => 'finlandia'],
            ['codeISO2' => 'FJ', 'codeISO3' => 'FJI', 'country_es' => 'Fiyi', 'tel_prefix' => '+679', 'language_field' => 'fiyi'],
            ['codeISO2' => 'FR', 'codeISO3' => 'FRA', 'country_es' => 'Francia', 'tel_prefix' => '+33', 'language_field' => 'francia'],
            ['codeISO2' => 'GA', 'codeISO3' => 'GAB', 'country_es' => 'Gabón', 'tel_prefix' => '+241', 'language_field' => 'gabon'],
            ['codeISO2' => 'GM', 'codeISO3' => 'GMB', 'country_es' => 'Gambia', 'tel_prefix' => '+220', 'language_field' => 'gambia'],
            ['codeISO2' => 'GE', 'codeISO3' => 'GEO', 'country_es' => 'Georgia', 'tel_prefix' => '+995', 'language_field' => 'georgia'],
            ['codeISO2' => 'GH', 'codeISO3' => 'GHA', 'country_es' => 'Ghana', 'tel_prefix' => '+233', 'language_field' => 'ghana'],
            ['codeISO2' => 'GI', 'codeISO3' => 'GIB', 'country_es' => 'Gibraltar', 'tel_prefix' => '+350', 'language_field' => 'gibraltar'],
            ['codeISO2' => 'GR', 'codeISO3' => 'GRC', 'country_es' => 'Grecia', 'tel_prefix' => '+30', 'language_field' => 'grecia'],
            ['codeISO2' => 'GL', 'codeISO3' => 'GRL', 'country_es' => 'Groenlandia', 'tel_prefix' => '+299', 'language_field' => 'groenlandia'],
            ['codeISO2' => 'GP', 'codeISO3' => 'GLP', 'country_es' => 'Guadalupe', 'tel_prefix' => '+590', 'language_field' => 'guadalupe'],
            ['codeISO2' => 'GU', 'codeISO3' => 'GUM', 'country_es' => 'Guam', 'tel_prefix' => '+1 671', 'language_field' => 'guam'],
            ['codeISO2' => 'GT', 'codeISO3' => 'GTM', 'country_es' => 'Guatemala', 'tel_prefix' => '+502', 'language_field' => 'guatemala'],
            ['codeISO2' => 'GN', 'codeISO3' => 'GIN', 'country_es' => 'Guinea', 'tel_prefix' => '+224', 'language_field' => 'guinea'],
            ['codeISO2' => 'GQ', 'codeISO3' => 'GNQ', 'country_es' => 'Guinea Ecuatorial', 'tel_prefix' => '+240', 'language_field' => 'guinea_ecuatorial'],
            ['codeISO2' => 'GW', 'codeISO3' => 'GNB', 'country_es' => 'Guinea-Bissáu', 'tel_prefix' => '+245', 'language_field' => 'guinea_bissau'],
            ['codeISO2' => 'GY', 'codeISO3' => 'GUY', 'country_es' => 'Guyana', 'tel_prefix' => '+592', 'language_field' => 'guyana'],
            ['codeISO2' => 'HT', 'codeISO3' => 'HTI', 'country_es' => 'Haití', 'tel_prefix' => '+509', 'language_field' => 'haiti'],
            ['codeISO2' => 'NL', 'codeISO3' => 'NLD', 'country_es' => 'Holanda', 'tel_prefix' => '+31', 'language_field' => 'holanda'],
            ['codeISO2' => 'HN', 'codeISO3' => 'HND', 'country_es' => 'Honduras', 'tel_prefix' => '+504', 'language_field' => 'honduras'],
            ['codeISO2' => 'HK', 'codeISO3' => 'HKG', 'country_es' => 'Hong Kong', 'tel_prefix' => '+852', 'language_field' => 'hong_kong'],
            ['codeISO2' => 'HU', 'codeISO3' => 'HUN', 'country_es' => 'Hungría', 'tel_prefix' => '+36', 'language_field' => 'hungria'],
            ['codeISO2' => 'IN', 'codeISO3' => 'IND', 'country_es' => 'India', 'tel_prefix' => '+91', 'language_field' => 'india'],
            ['codeISO2' => 'ID', 'codeISO3' => 'IDN', 'country_es' => 'Indonesia', 'tel_prefix' => '+62', 'language_field' => 'indonesia'],
            ['codeISO2' => 'IQ', 'codeISO3' => 'IRQ', 'country_es' => 'Irak', 'tel_prefix' => '+964', 'language_field' => 'irak'],
            ['codeISO2' => 'IR', 'codeISO3' => 'IRN', 'country_es' => 'Irán', 'tel_prefix' => '+98', 'language_field' => 'iran'],
            ['codeISO2' => 'IE', 'codeISO3' => 'IRL', 'country_es' => 'Irlanda', 'tel_prefix' => '+353', 'language_field' => 'irlanda'],
            ['codeISO2' => 'IM', 'codeISO3' => 'IMN', 'country_es' => 'Isla de Man', 'tel_prefix' => '+44', 'language_field' => 'isla_de_man'],
            ['codeISO2' => 'NF', 'codeISO3' => 'NFK', 'country_es' => 'Isla Norfolk', 'tel_prefix' => '+672', 'language_field' => 'isla_norfolk'],
            ['codeISO2' => 'IS', 'codeISO3' => 'ISL', 'country_es' => 'Islandia', 'tel_prefix' => '+354', 'language_field' => 'islandia'],
            ['codeISO2' => 'KY', 'codeISO3' => 'CYM', 'country_es' => 'Islas Caimán', 'tel_prefix' => '+1-345', 'language_field' => 'islas_caiman'],
            ['codeISO2' => 'CK', 'codeISO3' => 'COK', 'country_es' => 'Islas Cook', 'tel_prefix' => '+682', 'language_field' => 'islas_cook'],
            ['codeISO2' => 'FO', 'codeISO3' => 'FRO', 'country_es' => 'Islas Feroe', 'tel_prefix' => '+298', 'language_field' => 'islas_feroe'],
            ['codeISO2' => 'FK', 'codeISO3' => 'FLK', 'country_es' => 'Islas Malvinas', 'tel_prefix' => '+500', 'language_field' => 'islas_malvinas'],
            ['codeISO2' => 'MP', 'codeISO3' => 'MNP', 'country_es' => 'Islas Marianas del Norte', 'tel_prefix' => '+1 670', 'language_field' => 'islas_marianas_del_norte'],
            ['codeISO2' => 'MH', 'codeISO3' => 'MHL', 'country_es' => 'Islas Marshall', 'tel_prefix' => '+692', 'language_field' => 'islas_marshall'],
            ['codeISO2' => 'PN', 'codeISO3' => 'PCN', 'country_es' => 'Islas Pitcairn', 'tel_prefix' => '+870', 'language_field' => 'islas_pitcairn'],
            ['codeISO2' => 'SB', 'codeISO3' => 'SLB', 'country_es' => 'Islas Salomón', 'tel_prefix' => '+677', 'language_field' => 'islas_salomon'],
            ['codeISO2' => 'VG', 'codeISO3' => 'VGB', 'country_es' => 'Islas Vírgenes Británicas', 'tel_prefix' => '+1 284', 'language_field' => 'islas_virgenes_britanicas'],
            ['codeISO2' => 'IL', 'codeISO3' => 'ISR', 'country_es' => 'Israel', 'tel_prefix' => '+972', 'language_field' => 'israel'],
            ['codeISO2' => 'IT', 'codeISO3' => 'ITA', 'country_es' => 'Italia', 'tel_prefix' => '+39', 'language_field' => 'italia'],
            ['codeISO2' => 'JM', 'codeISO3' => 'JAM', 'country_es' => 'Jamaica', 'tel_prefix' => '+1', 'language_field' => 'jamaica'],
            ['codeISO2' => 'JP', 'codeISO3' => 'JPN', 'country_es' => 'Japón', 'tel_prefix' => '+81', 'language_field' => 'japon'],
            ['codeISO2' => 'JO', 'codeISO3' => 'JOR', 'country_es' => 'Jordania', 'tel_prefix' => '+962', 'language_field' => 'jordania'],
            ['codeISO2' => 'KZ', 'codeISO3' => 'KAZ', 'country_es' => 'Kazajistán', 'tel_prefix' => '+7', 'language_field' => 'kazajistan'],
            ['codeISO2' => 'KE', 'codeISO3' => 'KEN', 'country_es' => 'Kenia', 'tel_prefix' => '+254', 'language_field' => 'kenia'],
            ['codeISO2' => 'KG', 'codeISO3' => 'KGZ', 'country_es' => 'Kirgizistán', 'tel_prefix' => '+996', 'language_field' => 'kirguizistan'],
            ['codeISO2' => 'KI', 'codeISO3' => 'KIR', 'country_es' => 'Kiribati', 'tel_prefix' => '+686', 'language_field' => 'kiribati'],
            ['codeISO2' => 'XK', 'codeISO3' => 'XKX', 'country_es' => 'Kosovo', 'tel_prefix' => '+381', 'language_field' => 'kosovo'],
            ['codeISO2' => 'KW', 'codeISO3' => 'KWT', 'country_es' => 'Kuwait', 'tel_prefix' => '+965', 'language_field' => 'kuwait'],
            ['codeISO2' => 'LA', 'codeISO3' => 'LAO', 'country_es' => 'Laos', 'tel_prefix' => '+856', 'language_field' => 'laos'],
            ['codeISO2' => 'LS', 'codeISO3' => 'LSO', 'country_es' => 'Lesoto', 'tel_prefix' => '+266', 'language_field' => 'lesoto'],
            ['codeISO2' => 'LV', 'codeISO3' => 'LVA', 'country_es' => 'Letonia', 'tel_prefix' => '+371', 'language_field' => 'letonia'],
            ['codeISO2' => 'LB', 'codeISO3' => 'LBN', 'country_es' => 'Líbano', 'tel_prefix' => '+961', 'language_field' => 'libano'],
            ['codeISO2' => 'LR', 'codeISO3' => 'LBR', 'country_es' => 'Liberia', 'tel_prefix' => '+231', 'language_field' => 'liberia'],
            ['codeISO2' => 'LY', 'codeISO3' => 'LBY', 'country_es' => 'Libia', 'tel_prefix' => '+218', 'language_field' => 'libia'],
            ['codeISO2' => 'LI', 'codeISO3' => 'LIE', 'country_es' => 'Liechtenstein', 'tel_prefix' => '+423', 'language_field' => 'liechtenstein'],
            ['codeISO2' => 'LT', 'codeISO3' => 'LTU', 'country_es' => 'Lituania', 'tel_prefix' => '+370', 'language_field' => 'lituania'],
            ['codeISO2' => 'LU', 'codeISO3' => 'LUX', 'country_es' => 'Luxemburgo', 'tel_prefix' => '+352', 'language_field' => 'luxemburgo'],
            ['codeISO2' => 'MO', 'codeISO3' => 'MAC', 'country_es' => 'Macao', 'tel_prefix' => '+853', 'language_field' => 'macao'],
            ['codeISO2' => 'MK', 'codeISO3' => 'MKD', 'country_es' => 'Macedonia', 'tel_prefix' => '+389', 'language_field' => 'macedonia'],
            ['codeISO2' => 'MG', 'codeISO3' => 'MDG', 'country_es' => 'Madagascar', 'tel_prefix' => '+261', 'language_field' => 'madagascar'],
            ['codeISO2' => 'MY', 'codeISO3' => 'MYS', 'country_es' => 'Malasia', 'tel_prefix' => '+60', 'language_field' => 'malasia'],
            ['codeISO2' => 'MW', 'codeISO3' => 'MWI', 'country_es' => 'Malaui', 'tel_prefix' => '+265', 'language_field' => 'malaui'],
            ['codeISO2' => 'MV', 'codeISO3' => 'MDV', 'country_es' => 'Maldivas', 'tel_prefix' => '+960', 'language_field' => 'maldivas'],
            ['codeISO2' => 'ML', 'codeISO3' => 'MLI', 'country_es' => 'Mali', 'tel_prefix' => '+223', 'language_field' => 'mali'],
            ['codeISO2' => 'MT', 'codeISO3' => 'MLT', 'country_es' => 'Malta', 'tel_prefix' => '+356', 'language_field' => 'malta'],
            ['codeISO2' => 'MA', 'codeISO3' => 'MAR', 'country_es' => 'Marruecos', 'tel_prefix' => '+212', 'language_field' => 'marruecos'],
            ['codeISO2' => 'MU', 'codeISO3' => 'MUS', 'country_es' => 'Mauricio', 'tel_prefix' => '+230', 'language_field' => 'mauricio'],
            ['codeISO2' => 'MR', 'codeISO3' => 'MRT', 'country_es' => 'Mauritania', 'tel_prefix' => '+222', 'language_field' => 'mauritania'],
            ['codeISO2' => 'MX', 'codeISO3' => 'MEX', 'country_es' => 'México', 'tel_prefix' => '+52', 'language_field' => 'mexico'],
            ['codeISO2' => 'FM', 'codeISO3' => 'FSM', 'country_es' => 'Micronesia', 'tel_prefix' => '+691', 'language_field' => 'micronesia'],
            ['codeISO2' => 'MD', 'codeISO3' => 'MDA', 'country_es' => 'Moldavia', 'tel_prefix' => '+373', 'language_field' => 'moldavia'],
            ['codeISO2' => 'MC', 'codeISO3' => 'MCO', 'country_es' => 'Mónaco', 'tel_prefix' => '+377', 'language_field' => 'monaco'],
            ['codeISO2' => 'MN', 'codeISO3' => 'MNG', 'country_es' => 'Mongolia', 'tel_prefix' => '+976', 'language_field' => 'mongolia'],
            ['codeISO2' => 'ME', 'codeISO3' => 'MNE', 'country_es' => 'Montenegro', 'tel_prefix' => '+382', 'language_field' => 'montenegro'],
            ['codeISO2' => 'MS', 'codeISO3' => 'MSR', 'country_es' => 'Montserrat', 'tel_prefix' => '+1 664', 'language_field' => 'montserrat'],
            ['codeISO2' => 'MZ', 'codeISO3' => 'MOZ', 'country_es' => 'Mozambique', 'tel_prefix' => '+258', 'language_field' => 'mozambique'],
            ['codeISO2' => 'NA', 'codeISO3' => 'NAM', 'country_es' => 'Namibia', 'tel_prefix' => '+264', 'language_field' => 'namibia'],
            ['codeISO2' => 'NR', 'codeISO3' => 'NRU', 'country_es' => 'Nauru', 'tel_prefix' => '+674', 'language_field' => 'nauru'],
            ['codeISO2' => 'NP', 'codeISO3' => 'NPL', 'country_es' => 'Nepal', 'tel_prefix' => '+977', 'language_field' => 'nepal'],
            ['codeISO2' => 'NI', 'codeISO3' => 'NIC', 'country_es' => 'Nicaragua', 'tel_prefix' => '+505', 'language_field' => 'nicaragua'],
            ['codeISO2' => 'NE', 'codeISO3' => 'NER', 'country_es' => 'Níger', 'tel_prefix' => '+227', 'language_field' => 'niger'],
            ['codeISO2' => 'NG', 'codeISO3' => 'NGA', 'country_es' => 'Nigeria', 'tel_prefix' => '+234', 'language_field' => 'nigeria'],
            ['codeISO2' => 'NU', 'codeISO3' => 'NIU', 'country_es' => 'Niue', 'tel_prefix' => '+683', 'language_field' => 'niue'],
            ['codeISO2' => 'NO', 'codeISO3' => 'NOR', 'country_es' => 'Noruega', 'tel_prefix' => '+47', 'language_field' => 'noruega'],
            ['codeISO2' => 'NC', 'codeISO3' => 'NCL', 'country_es' => 'Nueva Caledonia', 'tel_prefix' => '+687', 'language_field' => 'nueva_caledonia'],
            ['codeISO2' => 'NZ', 'codeISO3' => 'NZL', 'country_es' => 'Nueva Zelanda', 'tel_prefix' => '+64', 'language_field' => 'nueva_zelanda'],
            ['codeISO2' => 'OM', 'codeISO3' => 'OMN', 'country_es' => 'Omán', 'tel_prefix' => '+968', 'language_field' => 'oman'],
            ['codeISO2' => 'PK', 'codeISO3' => 'PAK', 'country_es' => 'Pakistán', 'tel_prefix' => '+92', 'language_field' => 'pakistan'],
            ['codeISO2' => 'PW', 'codeISO3' => 'PLW', 'country_es' => 'Palau', 'tel_prefix' => '+680', 'language_field' => 'palau'],
            ['codeISO2' => 'PA', 'codeISO3' => 'PAN', 'country_es' => 'Panamá', 'tel_prefix' => '+507', 'language_field' => 'panama'],
            ['codeISO2' => 'PG', 'codeISO3' => 'PNG', 'country_es' => 'Papúa Nueva Guinea', 'tel_prefix' => '+675', 'language_field' => 'papua_nueva_guinea'],
            ['codeISO2' => 'PY', 'codeISO3' => 'PRY', 'country_es' => 'Paraguay', 'tel_prefix' => '+595', 'language_field' => 'paraguay'],
            ['codeISO2' => 'PE', 'codeISO3' => 'PER', 'country_es' => 'Perú', 'tel_prefix' => '+51', 'language_field' => 'peru'],
            ['codeISO2' => 'PF', 'codeISO3' => 'PYF', 'country_es' => 'Polinesia Francesa', 'tel_prefix' => '+689', 'language_field' => 'polinesia_francesa'],
            ['codeISO2' => 'PL', 'codeISO3' => 'POL', 'country_es' => 'Polonia', 'tel_prefix' => '+48', 'language_field' => 'polonia'],
            ['codeISO2' => 'PT', 'codeISO3' => 'PRT', 'country_es' => 'Portugal', 'tel_prefix' => '+351', 'language_field' => 'portugal'],
            ['codeISO2' => 'PR', 'codeISO3' => 'PRI', 'country_es' => 'Puerto Rico', 'tel_prefix' => '+1', 'language_field' => 'puerto_rico'],
            ['codeISO2' => 'QA', 'codeISO3' => 'QAT', 'country_es' => 'Qatar', 'tel_prefix' => '+974', 'language_field' => 'qatar'],
            ['codeISO2' => 'GB', 'codeISO3' => 'GBR', 'country_es' => 'Reino Unido', 'tel_prefix' => '+44', 'language_field' => 'reino_unido'],
            ['codeISO2' => 'CF', 'codeISO3' => 'CAF', 'country_es' => 'República Centroafricana', 'tel_prefix' => '+236', 'language_field' => 'republica_centroafricana'],
            ['codeISO2' => 'CZ', 'codeISO3' => 'CZE', 'country_es' => 'República Checa', 'tel_prefix' => '+420', 'language_field' => 'republica_checa'],
            ['codeISO2' => 'SS', 'codeISO3' => 'SSD', 'country_es' => 'República de Sudán del Sur', 'tel_prefix' => '+211', 'language_field' => 'republica_de_sudan_del_sur'],
            ['codeISO2' => 'CG', 'codeISO3' => 'COG', 'country_es' => 'República del Congo', 'tel_prefix' => '+242', 'language_field' => 'republica_del_congo'],
            ['codeISO2' => 'CD', 'codeISO3' => 'COD', 'country_es' => 'República Democrática del Congo', 'tel_prefix' => '+243', 'language_field' => 'republica_democratica_del_congo'],
            ['codeISO2' => 'DO', 'codeISO3' => 'DOM', 'country_es' => 'República Dominicana', 'tel_prefix' => '+1', 'language_field' => 'republica_dominicana'],
            ['codeISO2' => 'RE', 'codeISO3' => 'REU', 'country_es' => 'Reunión', 'tel_prefix' => '+262', 'language_field' => 'reunion'],
            ['codeISO2' => 'RW', 'codeISO3' => 'RWA', 'country_es' => 'Ruanda', 'tel_prefix' => '+250', 'language_field' => 'ruanda'],
            ['codeISO2' => 'RO', 'codeISO3' => 'ROU', 'country_es' => 'Rumanía', 'tel_prefix' => '+40', 'language_field' => 'rumania'],
            ['codeISO2' => 'RU', 'codeISO3' => 'RUS', 'country_es' => 'Rusia', 'tel_prefix' => '+7', 'language_field' => 'rusia'],
            ['codeISO2' => 'WS', 'codeISO3' => 'WSM', 'country_es' => 'Samoa', 'tel_prefix' => '+685', 'language_field' => 'samoa'],
            ['codeISO2' => 'AS', 'codeISO3' => 'ASM', 'country_es' => 'Samoa Americana', 'tel_prefix' => '+1 684', 'language_field' => 'samoa_americana'],
            ['codeISO2' => 'BL', 'codeISO3' => 'BLM', 'country_es' => 'San Bartolomé', 'tel_prefix' => '+590', 'language_field' => 'san_bartolome'],
            ['codeISO2' => 'KN', 'codeISO3' => 'KNA', 'country_es' => 'San Cristóbal y Nevis', 'tel_prefix' => '+1', 'language_field' => 'san_cristobal_y_nevis'],
            ['codeISO2' => 'SM', 'codeISO3' => 'SMR', 'country_es' => 'San Marino', 'tel_prefix' => '+378', 'language_field' => 'san_marino'],
            ['codeISO2' => 'MF', 'codeISO3' => 'MAF', 'country_es' => 'San Martín', 'tel_prefix' => '+1 599', 'language_field' => 'san_martin'],
            ['codeISO2' => 'PM', 'codeISO3' => 'SPM', 'country_es' => 'San Pedro y Miquelón', 'tel_prefix' => '+508', 'language_field' => 'san_pedro_y_miquelon'],
            ['codeISO2' => 'VC', 'codeISO3' => 'VCT', 'country_es' => 'San Vicente y las Granadinas', 'tel_prefix' => '+1', 'language_field' => 'san_vicente_y_las_granadinas'],
            ['codeISO2' => 'SH', 'codeISO3' => 'SHN', 'country_es' => 'Santa Elena', 'tel_prefix' => '+290', 'language_field' => 'santa_elena'],
            ['codeISO2' => 'LC', 'codeISO3' => 'LCA', 'country_es' => 'Santa Lucía', 'tel_prefix' => '+1', 'language_field' => 'santa_lucia'],
            ['codeISO2' => 'ST', 'codeISO3' => 'STP', 'country_es' => 'Santo Tomé y Príncipe', 'tel_prefix' => '+239', 'language_field' => 'santo_tome_y_principe'],
            ['codeISO2' => 'SN', 'codeISO3' => 'SEN', 'country_es' => 'Senegal', 'tel_prefix' => '+221', 'language_field' => 'senegal'],
            ['codeISO2' => 'RS', 'codeISO3' => 'SRB', 'country_es' => 'Serbia', 'tel_prefix' => '+381', 'language_field' => 'serbia'],
            ['codeISO2' => 'SC', 'codeISO3' => 'SYC', 'country_es' => 'Seychelles', 'tel_prefix' => '+248', 'language_field' => 'seychelles'],
            ['codeISO2' => 'SL', 'codeISO3' => 'SLE', 'country_es' => 'Sierra Leona', 'tel_prefix' => '+232', 'language_field' => 'sierra_leona'],
            ['codeISO2' => 'SG', 'codeISO3' => 'SGP', 'country_es' => 'Singapur', 'tel_prefix' => '+65', 'language_field' => 'singapur'],
            ['codeISO2' => 'SY', 'codeISO3' => 'SYR', 'country_es' => 'Siria', 'tel_prefix' => '+963', 'language_field' => 'siria'],
            ['codeISO2' => 'SO', 'codeISO3' => 'SOM', 'country_es' => 'Somalia', 'tel_prefix' => '+252', 'language_field' => 'somalia'],
            ['codeISO2' => 'LK', 'codeISO3' => 'LKA', 'country_es' => 'Sri Lanka', 'tel_prefix' => '+94', 'language_field' => 'sri_lanka'],
            ['codeISO2' => 'ZA', 'codeISO3' => 'ZAF', 'country_es' => 'Sudáfrica', 'tel_prefix' => '+27', 'language_field' => 'sudafrica'],
            ['codeISO2' => 'SD', 'codeISO3' => 'SDN', 'country_es' => 'Sudán', 'tel_prefix' => '+249', 'language_field' => 'sudan'],
            ['codeISO2' => 'SE', 'codeISO3' => 'SWE', 'country_es' => 'Suecia', 'tel_prefix' => '+46', 'language_field' => 'suecia'],
            ['codeISO2' => 'CH', 'codeISO3' => 'CHE', 'country_es' => 'Suiza', 'tel_prefix' => '+41', 'language_field' => 'suiza'],
            ['codeISO2' => 'SR', 'codeISO3' => 'SUR', 'country_es' => 'Surinam', 'tel_prefix' => '+597', 'language_field' => 'surinam'],
            ['codeISO2' => 'SZ', 'codeISO3' => 'SWZ', 'country_es' => 'Swazilandia', 'tel_prefix' => '+268', 'language_field' => 'swazilandia'],
            ['codeISO2' => 'TH', 'codeISO3' => 'THA', 'country_es' => 'Tailandia', 'tel_prefix' => '+66', 'language_field' => 'tailandia'],
            ['codeISO2' => 'TW', 'codeISO3' => 'TWN', 'country_es' => 'Taiwán', 'tel_prefix' => '+886', 'language_field' => 'taiwan'],
            ['codeISO2' => 'TZ', 'codeISO3' => 'TZA', 'country_es' => 'Tanzania', 'tel_prefix' => '+255', 'language_field' => 'tanzania'],
            ['codeISO2' => 'TJ', 'codeISO3' => 'TJK', 'country_es' => 'Tayikistán', 'tel_prefix' => '+992', 'language_field' => 'tayikistan'],
            ['codeISO2' => 'TL', 'codeISO3' => 'TLS', 'country_es' => 'Timor Oriental', 'tel_prefix' => '+670', 'language_field' => 'timor_oriental'],
            ['codeISO2' => 'TG', 'codeISO3' => 'TGO', 'country_es' => 'Togo', 'tel_prefix' => '+228', 'language_field' => 'togo'],
            ['codeISO2' => 'TK', 'codeISO3' => 'TKL', 'country_es' => 'Tokelau', 'tel_prefix' => '+690', 'language_field' => 'tokelau'],
            ['codeISO2' => 'TT', 'codeISO3' => 'TTO', 'country_es' => 'Trinidad y Tobago', 'tel_prefix' => '+1', 'language_field' => 'trinidad_y_tobago'],
            ['codeISO2' => 'TN', 'codeISO3' => 'TUN', 'country_es' => 'Túnez', 'tel_prefix' => '+216', 'language_field' => 'tunez'],
            ['codeISO2' => 'TM', 'codeISO3' => 'TKM', 'country_es' => 'Turkmenistán', 'tel_prefix' => '+993', 'language_field' => 'turkmenistan'],
            ['codeISO2' => 'TR', 'codeISO3' => 'TUR', 'country_es' => 'Turquía', 'tel_prefix' => '+90', 'language_field' => 'turquia'],
            ['codeISO2' => 'TV', 'codeISO3' => 'TUV', 'country_es' => 'Tuvalu', 'tel_prefix' => '+688', 'language_field' => 'tuvalu'],
            ['codeISO2' => 'UA', 'codeISO3' => 'UKR', 'country_es' => 'Ucrania', 'tel_prefix' => '+380', 'language_field' => 'ucrania'],
            ['codeISO2' => 'UG', 'codeISO3' => 'UGA', 'country_es' => 'Uganda', 'tel_prefix' => '+256', 'language_field' => 'uganda'],
            ['codeISO2' => 'UY', 'codeISO3' => 'URY', 'country_es' => 'Uruguay', 'tel_prefix' => '+598', 'language_field' => 'uruguay'],
            ['codeISO2' => 'UZ', 'codeISO3' => 'UZB', 'country_es' => 'Uzbekistán', 'tel_prefix' => '+998', 'language_field' => 'uzbekistan'],
            ['codeISO2' => 'VU', 'codeISO3' => 'VUT', 'country_es' => 'Vanuatu', 'tel_prefix' => '+678', 'language_field' => 'vanuatu'],
            ['codeISO2' => 'VE', 'codeISO3' => 'VEN', 'country_es' => 'Venezuela', 'tel_prefix' => '+58', 'language_field' => 'venezuela'],
            ['codeISO2' => 'VN', 'codeISO3' => 'VNM', 'country_es' => 'Vietnam', 'tel_prefix' => '+84', 'language_field' => 'vietnam'],
            ['codeISO2' => 'YE', 'codeISO3' => 'YEM', 'country_es' => 'Yemen', 'tel_prefix' => '+967', 'language_field' => 'yemen'],
            ['codeISO2' => 'ZM', 'codeISO3' => 'ZMB', 'country_es' => 'Zambia', 'tel_prefix' => '+260', 'language_field' => 'zambia'],
            ['codeISO2' => 'ZW', 'codeISO3' => 'ZWE', 'country_es' => 'Zimbabue', 'tel_prefix' => '+263', 'language_field' => 'zimbabue']
            
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};
